[package]
name = "AoC-Claude-Rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day1"
path = "src/puzzles/day1/solution.rs"

[[bin]]
name = "day2"
path = "src/puzzles/day2/solution.rs"